version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: esbuild-wasm
    versions:
    - 0.10.0
    - 0.10.1
    - 0.11.0
    - 0.11.10
    - 0.11.12
    - 0.11.13
    - 0.11.15
    - 0.11.2
    - 0.11.3
    - 0.11.5
    - 0.11.6
    - 0.11.9
    - 0.9.3
    - 0.9.5
    - 0.9.6
    - 0.9.7
  - dependency-name: "@testing-library/user-event"
    versions:
    - 13.0.0
    - 13.0.1
    - 13.0.10
    - 13.0.13
    - 13.0.16
    - 13.0.2
    - 13.0.6
    - 13.0.7
    - 13.1.1
    - 13.1.2
    - 13.1.3
    - 13.1.5
  - dependency-name: react-dom
    versions:
    - 17.0.2
  - dependency-name: react
    versions:
    - 17.0.2
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.3
  - dependency-name: typescript
    versions:
    - 4.2.4
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.6
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
    - 26.0.22
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
